Slides & solutions
digitalearthafrica/deafrica-training-workshop pull request #40
Opened 2020-09-11 03:28 UTC by eefaye

Slides

- Week 2 and Week 3 videos are now accompanied with a link to download the slides

- Week 1 video does not have up-to-date slides on the Google Drive. Also, I think it would look messy to have it on the front page so am happy to leave it off. Thoughts?

Solutions

- Solutions page for Session 3 has been added. The 'Quiz' elements were removed, I assume we will add them back in when we have one

- Solutions document for Session 3 exercises has been added to _static, with annotations as per Session 2's. Thanks John for the base file!

 - Solutions pages have been renamed with the prefix `s2`, `s3`, for session 2, session 3 etc. to avoid confusing them in JupyterLab when they are all open at the same time

 - Solutions document names should match the file name specified in the exercise, plus `_solution`, and should be in the relevant session subfolder in _static

Note: old PR was mistakenly branched off week 4 content instead of master; has been fixed here.

2020-09-11 05:05 UTC, caitlinadams requested changes
Hey @eefaye -- thanks for your work on this, it's really helpful to have this implemented. 

We typically launch the quiz and the solution simultaneously. Would you mind adding the Quiz section back in? Just remove the hyperlink (or leave it blank) and I will update it once we have it.

Since we launch them simultaneously, I won't merge this PR until Monday or Tuesday next week (depending on when the quiz is ready).

2020-09-11 05:06 UTC, caitlinadams commented
I agree with you about the session 1 slides, we can leave them off, I think.

2020-09-15 01:35 UTC, eefaye commented
@andrewdhicks when you have reviewed the quiz I think we'll be good to go.

2020-09-15 04:50 UTC, caitlinadams approved these changes

2020-09-15 04:50 UTC, merged